import './BrowserMockup.css';

// Screenshots ship as four widths (400/600/1000/native) generated by sharp
// from the source webp. Derives "/images/crf.webp" -> "/images/crf-400.webp" etc.
function srcSetFor(image) {
  const dot = image.lastIndexOf('.');
  const base = image.slice(0, dot);
  const ext = image.slice(dot);
  return `${base}-400${ext} 400w, ${base}-600${ext} 600w, ${base}-1000${ext} 1000w, ${image} 1400w`;
}

// Browser-chrome frame. Renders a real screenshot when `image` is provided,
// otherwise a labeled placeholder. Screenshots are cropped to the site's hero
// and shown top-anchored so the frame reads like a live browser window.
export default function BrowserMockup({
  url,
  className = '',
  image,
  imageAlt,
  imageWidth,
  imageHeight,
  sizes,
  loading = 'lazy',
}) {
  return (
    <div className={`mockup ${className}`.trim()}>
      <div className="mockup__toolbar">
        <span className="mockup__dots" aria-hidden="true">
          <span />
          <span />
          <span />
        </span>
        <span className="mockup__url">{url}</span>
      </div>
      <div className="mockup__screen">
        {image ? (
          <img
            className="mockup__img"
            src={image}
            srcSet={srcSetFor(image)}
            sizes={sizes}
            alt={imageAlt || `Screenshot of ${url}`}
            width={imageWidth}
            height={imageHeight}
            loading={loading}
            decoding="async"
          />
        ) : (
          <span className="mockup__placeholder">Screenshot: {url}</span>
        )}
      </div>
    </div>
  );
}
